name: Engagement Bot

on:
  # Scheduled triggers (times are in UTC)
  schedule:
    - cron: '0 14 * * *'  # 9:00 AM Eastern Standard Time (14:00 UTC)
    - cron: '0 2 * * *'   # 9:00 PM Eastern Standard Time (02:00 UTC)
  # Manual trigger
  workflow_dispatch:

jobs:
  run-engagement-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv pytz openai requests-oauthlib

      - name: Run Engagement Bot
        run: python engagement_bot.py
